# Configuration for chart-testing action
remote: origin
target-branch: main
chart-dirs:
  - .
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
check-version-increment: true
validate-maintainers: false
