{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "packmind.fullname" . }}-redis
  labels:
    {{- include "packmind.redis.labels" . | nindent 4 }}
  {{- with (include "packmind.annotations" .) }}
  annotations:
    {{- if . }}
    {{- . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "packmind.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.redis.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with (include "packmind.annotations" .) }}
        {{- if . }}
        {{- . | nindent 8 }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "packmind.redis.selectorLabels" . | nindent 8 }}
        {{- with .Values.redis.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "packmind.imagePullSecrets" . | nindent 6 }}
      {{- include "packmind.serviceAccountNameField" . | nindent 6 }}
      {{- include "packmind.podSecurityContextField" (dict "context" . "component" "redis") | nindent 6 }}
      containers:
        - name: redis
          {{- include "packmind.securityContextField" (dict "context" . "component" "redis") | nindent 10 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          {{- if .Values.redis.auth.enabled }}
          env:
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                {{- if .Values.redis.auth.enabled }}
                - -a
                - {{ .Values.redis.auth.password | quote }}
                {{- end }}
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                {{- if .Values.redis.auth.enabled }}
                - -a
                - {{ .Values.redis.auth.password | quote }}
                {{- end }}
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
            {{- include "packmind.serviceVolumeMounts" (dict "component" "redis" "context" .) | nindent 12 }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "packmind.fullname" . }}-redis-data
        {{- include "packmind.serviceVolumes" (dict "component" "redis" "context" .) | nindent 8 }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
