{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "packmind.serviceAccountName" . }}
  labels:
    {{- include "packmind.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "packmind.annotations" .) }}
    {{- if . }}
    {{- . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
