{{- range $name, $config := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "packmind.fullname" $ }}-{{ $name }}
  labels:
    {{- include "packmind.labels" $ | nindent 4 }}
  {{- with (include "packmind.annotations" $) }}
  annotations:
    {{- if . }}
    {{- . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  {{- toYaml $config.data | nindent 2 }}
{{- end }}
