{{- if .Values.mcpServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "packmind.fullname" . }}-mcp-server
  labels:
    {{- include "packmind.mcpServer.labels" . | nindent 4 }}
  {{- with (include "packmind.annotations" .) }}
  annotations:
    {{- if . }}
    {{- . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if not .Values.mcpServer.autoscaling.enabled }}
  replicas: {{ .Values.mcpServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "packmind.mcpServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.mcpServer.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with (include "packmind.annotations" .) }}
        {{- if . }}
        {{- . | nindent 8 }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "packmind.mcpServer.selectorLabels" . | nindent 8 }}
        {{- with .Values.mcpServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "packmind.imagePullSecrets" . | nindent 6 }}
      {{- include "packmind.serviceAccountNameField" . | nindent 6 }}
      {{- include "packmind.podSecurityContextField" (dict "context" . "component" "mcpServer") | nindent 6 }}
      containers:
        - name: mcp-server
          {{- include "packmind.securityContextField" (dict "context" . "component" "mcpServer") | nindent 10 }}
          image: "{{ .Values.mcpServer.image.repository }}:{{ .Values.mcpServer.image.tag }}"
          imagePullPolicy: {{ .Values.mcpServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mcpServer.service.targetPort }}
              protocol: TCP
          env:
            {{- include "packmind.allEnvVars" (dict "component" "mcpServer" "context" .) | nindent 12 }}
            {{- if .Values.mcpServer.caCerts.enabled }}
            - name: NODE_EXTRA_CA_CERTS
              value: /ca-certs/{{ .Values.mcpServer.caCerts.secret.key }}
            {{- end }}
          {{- with .Values.mcpServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mcpServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.mcpServer.resources | nindent 12 }}
          volumeMounts:
            {{- include "packmind.serviceVolumeMounts" (dict "component" "mcpServer" "context" .) | nindent 12 }}
      volumes:
        {{- include "packmind.serviceVolumes" (dict "component" "mcpServer" "context" .) | nindent 8 }}
      {{- with .Values.mcpServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcpServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcpServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
