{{- if and .Values.dockerRegistry.enabled (not .Values.dockerRegistry.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "packmind.fullname" . }}-registry-secret
  labels:
    {{- include "packmind.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
  {{- with (include "packmind.annotations" .) }}
  annotations:
    {{- if . }}
    {{- . | nindent 4 }}
    {{- end }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.dockerRegistry.registry .Values.dockerRegistry.username .Values.dockerRegistry.password .Values.dockerRegistry.email (printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc) | b64enc }}
{{- end }}
