{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "packmind.fullname" . }}-api
  labels:
    {{- include "packmind.api.labels" . | nindent 4 }}
  {{- include "packmind.mergedAnnotations" (dict "serviceAnnotations" .Values.api.service.annotations "context" .) | nindent 2 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "packmind.api.selectorLabels" . | nindent 4 }}
{{- end }}
